bool targeting_enabled

string classifier_name
string classifier_state

string image_topic
string depth_map_topic
string pointcloud_topic

string available_classes_list
string selected_classes_list
string selected_classes_depth_list

string available_targets_list
string selected_target

float32 image_fov_vert_degs 
float32 image_fov_horz_degs 

float32 target_box_reduction_percent 
float32 default_target_depth_m 
float32 target_min_points 
float32 target_age_filter 

#string current_targets_list
#string lost_targets_list
