# This message details the NEPI node's data saving settings.

# The save_continuous field provides the on/off mechanism for traditional data saving
bool save_continuous

# The save_raw field works in conjunction with the save_continuous field to capture "raw" data alongside
# the standard data product(s). The meanings of "raw" and "standard" here are dependent on the specific
# node
bool save_raw
