#Query Automation Manager system status
string script
---
float64 cpu_percent
float64 memory_percent
float64 run_time_s
float64 cumulative_run_time_s
int64 file_size_bytes
int32 started_runs
int32 completed_runs
int32 error_runs
int32 stopped_manually
bool auto_start_enabled
int64 log_size_bytes
