# Service file for the list of object classifiers supported by this device

---
string CLASSIFIER_STATE_STOPPED=Stopped
string CLASSIFIER_STATE_LOADING=Loading
string CLASSIFIER_STATE_RUNNING=Running

string selected_img_topic
string selected_classifier
string classifier_state
