# This service definition provides the capabilities report for a NEPI LSX driver node

---
bool has_standby_mode
bool has_on_off_control
bool has_intensity_control
bool has_color_control
string color_options_list
bool has_kelvin_control
int32 kelvin_min
int32 kelvin_max
bool has_blink_control
bool has_hw_strobe
bool reports_temperature
bool reports_power
