string name
---
string pkg_name
string group_name
string node_name
string mgr_file
string mgr_path   
string[] rui_files_list
string rui_main_file
string rui_main_class  
string rui_menu_name

string description
bool active_state
int32 order
string msg_str

