# Service file for an Operating Environment Query. Response
# is a string specifying the operating environment, which
# typically should match one of the defined constants. Note
# that configuration and calibration files may be located based
# on the response, so it is generally not advised to use
# strings outside this range unless you really know what you
# are doing.

---
string OP_ENV_AIR=air
string OP_ENV_WATER=water

string op_env