# This service provides a mechanism to request the software update status fields
# The response fields provide details about the current software updatability and status

---
# Response

# Location that is checked for a new system image
string new_sys_img_staging_device

# Free space on staging device
float32 new_sys_img_staging_device_free_mb

# System image filename
string new_sys_img

# System image filesize
float32 new_sys_img_size_mb

# System image version
string new_sys_img_version