# This service provides a mechanism to request the static system definitions.
# These definitions provides detail about the form and composition of the
# (dynamic) SystemStaus message.

---
nepi_ros_interfaces/SystemDefs defs