# This service definition provides the system storage folder request and response
# Type of folder/subdir being requested (data, logs, ai_models, automation_scripts, nepi_full_img, nepi_full_img_archive)
string type
---
# System path to requested folder
string folder_path

