# This service definition provides the current wifi settings

---
bool has_wifi
bool wifi_ap_enabled
string wifi_ap_ssid
string wifi_ap_passphrase
bool wifi_client_enabled
bool wifi_client_connected
string wifi_client_ssid
string wifi_client_passphrase
string[] available_networks
bool internet_connected
